function grid = computeVoronoiEdgeLength(grid)
% Function to compute the lengths of edges between the voronoi cells generated by x_i and x_j

M = sparse(grid.N,grid.N);

vol = zeros(grid.N, 1);
for i=1:grid.N
	cell_i = grid.C{i};

    % Firstly, we compute the volume of the dual cells
	vol(i) = polyarea(grid.V(cell_i,1), grid.V(cell_i,2));

    % Now, we
	for j=(i+1):grid.N
        cell_j = grid.C{j}

		pnts = intersect(grid.C{i},grid.C{j});
		if length(pnts) == 2 && all(pnts ~= 1)
			M(i,j) = sqrt(sum(diff(grid.V(pnts,:)).^2));
            keyboard
		end
	end
end
M = M + M';


end
